---
apiVersion: v1
kind: Service
metadata:
  name: simulator-spi
  labels:
    app: simulator-spi
spec:
  type: ClusterIP
  selector:
    app: simulator-spi
  ports:
    - name: http
      port: 3000
      targetPort: 3000
